# Generated by Django 4.0.4 on 2022-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_bid_category_lot_watchlist_watchlist_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='category',
        ),
        migrations.AddField(
            model_name='lot',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_lot', to='auctions.category'),
        ),
    ]
